"use client";

import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import type { ActionItem, BoardMessage, BoardOutput, Decision, Source, ToolInfo } from '@/lib/boardroom-api';
import type { SeatedAgent } from './boardroomState';

const safeUrl = (u: string) => (/^https?:\/\//i.test(u) ? u : '#');

const KIND_STYLE: Record<string, string> = {
  analysis: 'border-white/10', challenge: 'border-rose-500/40 bg-rose-500/5', response: 'border-emerald-500/30 bg-emerald-500/5', feedback: 'border-blue-500/30',
};

export function DiscussionPanel({ messages, agents }: { messages: BoardMessage[]; agents: SeatedAgent[] }) {
  if (!messages.length) return <Empty text="The discussion will appear here once the team starts working." />;
  const name = (id?: string) => agents.find((a) => a.id === id)?.role ?? id;
  return (
    <ol className="space-y-3">
      {messages.map((m) => (
        <li key={m.id} className={`rounded-xl border p-4 glass ${KIND_STYLE[m.kind] ?? 'border-white/10'}`}>
          <div className="flex flex-wrap items-center gap-2 text-xs mb-2">
            <span className="font-semibold text-white">{m.agent_name}</span>
            <span className="px-1.5 py-0.5 rounded bg-white/5 text-gray-400">
              {m.kind === 'challenge' ? `challenges ${name(m.target)}` : m.kind === 'response' ? 'responds' : m.kind === 'feedback' ? 'your feedback' : 'analysis'}
            </span>
            {m.severity && <span className="text-rose-300">{m.severity} severity</span>}
            {typeof m.confidence === 'number' && <span className="text-gray-500">confidence {(m.confidence * 100).toFixed(0)}%</span>}
            {m.position_changed && <span className="text-emerald-300">changed position</span>}
          </div>
          <div className="prose prose-invert prose-sm max-w-none text-gray-200 text-sm [&_p]:my-1.5 [&_ul]:my-1.5 [&_ul]:list-disc [&_ul]:pl-5">
            <ReactMarkdown>{m.content}</ReactMarkdown>
          </div>
          {!!m.key_points?.length && (
            <ul className="mt-2 flex flex-wrap gap-1.5">
              {m.key_points.map((k, i) => <li key={i} className="text-[11px] px-2 py-0.5 rounded-full bg-white/5 text-gray-300">{k}</li>)}
            </ul>
          )}
          {!!m.citations?.length && <div className="mt-2 text-[11px] text-blue-300">Sources: {m.citations.join(', ')}</div>}
        </li>
      ))}
    </ol>
  );
}

export function SourcesPanel({ sources, live }: { sources: Source[]; live: boolean }) {
  if (!sources.length) {
    return <Empty text={live ? 'No live sources yet.' : 'No live sources were retrieved for this work. Any findings rely on general model knowledge.'} />;
  }
  return (
    <ul className="space-y-2">
      {sources.map((s) => (
        <li key={s.id} className="glass rounded-xl p-3 text-sm">
          <div className="flex items-start gap-2">
            <span className="text-[11px] font-mono text-blue-300 mt-0.5">[{s.id}]</span>
            <div className="min-w-0">
              <a href={safeUrl(s.url)} target="_blank" rel="noopener noreferrer" className="text-white hover:underline break-words">{s.title}</a>
              <div className="text-[11px] text-gray-500 truncate">{s.url}</div>
              {s.snippet && <p className="text-xs text-gray-400 mt-1">{s.snippet}</p>}
              {s.query && <p className="text-[10px] text-gray-600 mt-1">via “{s.query}”</p>}
            </div>
          </div>
        </li>
      ))}
    </ul>
  );
}

export function TeamPanel({ agents, rationale, tools }: { agents: SeatedAgent[]; rationale: string; tools: Record<string, ToolInfo> }) {
  if (!agents.length) return <Empty text="The Board Architect is still designing the team." />;
  return (
    <div className="space-y-3">
      {rationale && <p className="text-sm text-gray-300 glass rounded-xl p-3"><span className="text-gray-500">Why this team: </span>{rationale}</p>}
      <p className="text-[11px] text-gray-500">Members are expert perspectives generated by AI, not real people.</p>
      {agents.map((a) => (
        <div key={a.id} className="glass rounded-xl p-4">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-semibold text-white text-sm">{a.perspective}</span>
            <span className="text-[10px] px-1.5 py-0.5 rounded bg-white/5 text-gray-400">{a.archetype.replace('_', ' ')}</span>
            {a.temporary && <span className="text-[10px] px-1.5 py-0.5 rounded bg-amber-500/10 text-amber-300">{a.left ? 'joined, then left' : 'specialist'}</span>}
          </div>
          {a.expertise && <p className="text-xs text-gray-400 mt-1">{a.expertise}</p>}
          {a.research_lens && <p className="text-xs text-gray-500 mt-1">Research lens: {a.research_lens}</p>}
          <div className="mt-2 flex flex-wrap gap-1.5">
            {a.tools.map((t) => {
              const info = tools[t];
              return (
                <span key={t} title={info?.implemented === false ? 'Planned: not yet available in this version' : 'Available'}
                  className={`text-[10px] px-2 py-0.5 rounded-full border ${info?.implemented === false ? 'border-white/10 text-gray-500 border-dashed' : 'border-emerald-500/30 text-emerald-300'}`}>
                  {info?.label ?? t}{info?.implemented === false ? ' (planned)' : ''}
                </span>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}

export function WorkspacePanel({ decisions, tasks, history }: { decisions: Decision[]; tasks: ActionItem[]; history: { stage: string; detail: string }[] }) {
  return (
    <div className="space-y-5">
      <Section title="Decisions" empty="No decisions extracted yet.">
        {decisions.map((d, i) => <li key={i} className="glass rounded-lg p-3 text-sm text-gray-200">{d.decision}{d.rationale && <div className="text-xs text-gray-500 mt-1">{d.rationale}</div>}</li>)}
      </Section>
      <Section title="Tasks" empty="No tasks extracted yet.">
        {tasks.map((t, i) => (
          <li key={i} className="glass rounded-lg p-3 text-sm text-gray-200 flex items-start gap-2">
            <span className={`text-[10px] px-1.5 py-0.5 rounded mt-0.5 ${t.priority === 'high' ? 'bg-rose-500/15 text-rose-300' : 'bg-white/5 text-gray-400'}`}>{t.priority ?? 'medium'}</span>
            <span>{t.task}{t.owner_role && <span className="text-xs text-gray-500"> · {t.owner_role}</span>}</span>
          </li>
        ))}
      </Section>
      <Section title="History" empty="">
        {history.map((h, i) => <li key={i} className="text-xs text-gray-400"><span className="text-gray-300">{h.stage}</span>{h.detail && ` · ${h.detail}`}</li>)}
      </Section>
    </div>
  );
}

function Section({ title, empty, children }: { title: string; empty: string; children: React.ReactNode }) {
  const items = React.Children.toArray(children);
  return (
    <section>
      <h3 className="text-xs uppercase tracking-wider text-gray-500 mb-2">{title}</h3>
      {items.length ? <ul className="space-y-2">{items}</ul> : empty ? <p className="text-xs text-gray-600">{empty}</p> : null}
    </section>
  );
}

export function DeliverablePanel({ outputs, sources, canRefine, refining, onRefine }: {
  outputs: BoardOutput[]; sources: Source[]; canRefine: boolean; refining: boolean; onRefine: (feedback: string) => void;
}) {
  const [picked, setPicked] = useState<number | null>(null);
  const [feedback, setFeedback] = useState('');
  const [copied, setCopied] = useState(false);
  if (!outputs.length) return <Empty text="The deliverable appears here once the team has finished and the quality review has passed." />;
  const out = outputs[picked ?? outputs.length - 1];
  const used = sources.filter((s) => out.sources_used.includes(s.id));

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(out.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* clipboard unavailable */ }
  };
  const download = () => {
    const url = URL.createObjectURL(new Blob([out.content], { type: 'text/markdown' }));
    const a = document.createElement('a');
    a.href = url;
    a.download = `${out.artifact_type.toLowerCase().replace(/\s+/g, '-')}-v${out.version}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        <span className="px-2.5 py-1 rounded-full bg-blue-500/15 text-blue-300 text-xs font-medium">{out.artifact_type}</span>
        {out.quality && (
          <span className={`px-2 py-1 rounded-full text-xs ${out.quality.issues.length ? 'bg-amber-500/10 text-amber-300' : 'bg-emerald-500/10 text-emerald-300'}`}
            title={out.quality.issues.join('\n')}>
            Quality review {out.quality.revised ? '· revised after review' : '· passed'}{typeof out.quality.score === 'number' ? ` · ${(out.quality.score * 100).toFixed(0)}%` : ''}
          </span>
        )}
        {outputs.length > 1 && (
          <select value={picked ?? outputs.length - 1} onChange={(e) => setPicked(Number(e.target.value))} aria-label="Version"
            className="bg-white/5 border border-white/10 rounded-lg text-xs px-2 py-1 text-gray-200">
            {outputs.map((o, i) => <option key={o.version} value={i} className="bg-[#0a0a1a]">Version {o.version}</option>)}
          </select>
        )}
        <span className="flex-1" />
        <button onClick={copy} className="text-xs px-3 py-1.5 rounded-lg bg-white/5 hover:bg-white/10 text-gray-200 cursor-pointer">{copied ? 'Copied' : 'Copy'}</button>
        <button onClick={download} className="text-xs px-3 py-1.5 rounded-lg bg-white/5 hover:bg-white/10 text-gray-200 cursor-pointer">Download .md</button>
      </div>

      {out.disclaimer && <div role="note" className="rounded-xl border border-amber-500/30 bg-amber-500/10 text-amber-200 text-xs p-3">{out.disclaimer}</div>}

      <article className="glass rounded-2xl p-6 prose prose-invert max-w-none text-gray-200 text-sm leading-relaxed [&_h1]:text-xl [&_h1]:font-bold [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:mt-5 [&_h3]:font-semibold [&_h3]:mt-4 [&_p]:my-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ol]:list-decimal [&_ol]:pl-5 [&_li]:my-0.5 [&_table]:w-full [&_td]:border [&_td]:border-white/10 [&_td]:p-1.5 [&_th]:border [&_th]:border-white/10 [&_th]:p-1.5 [&_a]:text-blue-300">
        <ReactMarkdown>{out.content}</ReactMarkdown>
      </article>

      {!!used.length && (
        <div className="text-xs text-gray-400">
          <div className="uppercase tracking-wider text-gray-500 mb-1">Sources cited</div>
          <ul className="space-y-1">{used.map((s) => <li key={s.id}>[{s.id}] <a className="text-blue-300 hover:underline" href={safeUrl(s.url)} target="_blank" rel="noopener noreferrer">{s.title}</a></li>)}</ul>
        </div>
      )}

      {canRefine && (
        <form onSubmit={(e) => { e.preventDefault(); if (feedback.trim() && !refining) { onRefine(feedback.trim()); setFeedback(''); } }} className="flex gap-2">
          <input value={feedback} onChange={(e) => setFeedback(e.target.value)} disabled={refining} maxLength={3000}
            placeholder="Review and refine: e.g. “make it cheaper”, “add a timeline”, “shorter”…"
            className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-500 focus-glow" />
          <button type="submit" disabled={refining || !feedback.trim()} className="px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 disabled:opacity-40 text-sm font-medium text-white cursor-pointer">
            {refining ? 'Refining…' : 'Refine'}
          </button>
        </form>
      )}
    </div>
  );
}

function Empty({ text }: { text: string }) {
  return <p className="text-sm text-gray-500 py-8 text-center">{text}</p>;
}
