"""Internal event bus event type constants."""

CHAT_COMPLETED = "chat.completed"
TASK_COMPLETED = "task.completed"
DOCUMENT_UPLOADED = "document.uploaded"
OBJECTIVE_CHANGED = "objective.changed"
BLUEPRINT_UPDATED = "blueprint.updated"
DISCOVERY_UPDATED = "discovery.updated"
MEMORY_UPDATED = "memory.updated"
DECISION_LOGGED = "decision.logged"
DELIVERABLE_CREATED = "deliverable.created"
ACTIVITY_CREATED = "activity.created"
