"""phase_2_models

Revision ID: 62b58d5a8c57
Revises: 95d18388241a
Create Date: 2026-06-11 23:47:33.923522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b58d5a8c57'
down_revision: Union[str, None] = '95d18388241a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("agent_communication_logs"):
        # Migration 001's Base.metadata.create_all() already materialized this
        # migration's tables against the current models.py on a fresh database.
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_communication_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('sender_agent', sa.String(), nullable=False),
    sa.Column('receiver_agent', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_communication_logs_created_at'), 'agent_communication_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_communication_logs_project_id'), 'agent_communication_logs', ['project_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager_agent', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_project_id'), 'departments', ['project_id'], unique=False)
    op.create_table('work_queues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_worker', sa.String(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_queues_department_id'), 'work_queues', ['department_id'], unique=False)
    op.create_index(op.f('ix_work_queues_project_id'), 'work_queues', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_queues_task_id'), 'work_queues', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_queues_task_id'), table_name='work_queues')
    op.drop_index(op.f('ix_work_queues_project_id'), table_name='work_queues')
    op.drop_index(op.f('ix_work_queues_department_id'), table_name='work_queues')
    op.drop_table('work_queues')
    op.drop_index(op.f('ix_departments_project_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_agent_communication_logs_project_id'), table_name='agent_communication_logs')
    op.drop_index(op.f('ix_agent_communication_logs_created_at'), table_name='agent_communication_logs')
    op.drop_table('agent_communication_logs')
    # ### end Alembic commands ###
