"""add field_confidences to company blueprint

Revision ID: 95d18388241a
Revises: 003_mvp_plan_approval
Create Date: 2026-06-11 23:23:58.147505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d18388241a'
down_revision: Union[str, None] = '003_mvp_plan_approval'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    existing_columns = [c["name"] for c in sa.inspect(bind).get_columns("company_blueprints")]
    # NOTE: migration 001 runs Base.metadata.create_all() against the current models,
    # which already includes this column. Guard against "already exists" so this
    # migration is safe to run both on a fresh DB and on one where 001 created everything.
    if "field_confidences" not in existing_columns:
        op.add_column('company_blueprints', sa.Column('field_confidences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('company_blueprints', 'field_confidences')
    # ### end Alembic commands ###
